project:
  type: website
  output-dir: docs
  resources:
    - dashboard.html
website:
  title: "Zizhi Xia"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: HW4     
        href: hw4_problem2.qmd   
    right:
      - icon: github
        href: https://github.com/ZizhiXia
      - icon: envelope
        href: mailto:zx2528@cumc.columbia.edu
      - text: LinkedIn
        href: https://www.linkedin.com/in/zizhi-xia-172575326/
format:
  html:
    theme: cosmo
